#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HAfitnessclub")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblJob(tblJob instance);
  partial void UpdatetblJob(tblJob instance);
  partial void DeletetblJob(tblJob instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HAfitnessclubConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblJob> tblJobs
	{
		get
		{
			return this.GetTable<tblJob>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblJob")]
public partial class tblJob : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _JID;
	
	private string _Fname;
	
	private string _Lname;
	
	private System.Nullable<decimal> _Phone;
	
	private System.Nullable<System.DateTime> _Bdate;
	
	private string _Address;
	
	private System.Nullable<decimal> _Pincode;
	
	private string _RName;
	
	private System.Nullable<decimal> _RPhone;
	
	private string _FileName;
	
	private string _FileLocation;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJIDChanging(int value);
    partial void OnJIDChanged();
    partial void OnFnameChanging(string value);
    partial void OnFnameChanged();
    partial void OnLnameChanging(string value);
    partial void OnLnameChanged();
    partial void OnPhoneChanging(System.Nullable<decimal> value);
    partial void OnPhoneChanged();
    partial void OnBdateChanging(System.Nullable<System.DateTime> value);
    partial void OnBdateChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPincodeChanging(System.Nullable<decimal> value);
    partial void OnPincodeChanged();
    partial void OnRNameChanging(string value);
    partial void OnRNameChanged();
    partial void OnRPhoneChanging(System.Nullable<decimal> value);
    partial void OnRPhoneChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnFileLocationChanging(string value);
    partial void OnFileLocationChanged();
    #endregion
	
	public tblJob()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int JID
	{
		get
		{
			return this._JID;
		}
		set
		{
			if ((this._JID != value))
			{
				this.OnJIDChanging(value);
				this.SendPropertyChanging();
				this._JID = value;
				this.SendPropertyChanged("JID");
				this.OnJIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this.OnFnameChanging(value);
				this.SendPropertyChanging();
				this._Fname = value;
				this.SendPropertyChanged("Fname");
				this.OnFnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this.OnLnameChanging(value);
				this.SendPropertyChanging();
				this._Lname = value;
				this.SendPropertyChanged("Lname");
				this.OnLnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bdate", DbType="Date")]
	public System.Nullable<System.DateTime> Bdate
	{
		get
		{
			return this._Bdate;
		}
		set
		{
			if ((this._Bdate != value))
			{
				this.OnBdateChanging(value);
				this.SendPropertyChanging();
				this._Bdate = value;
				this.SendPropertyChanged("Bdate");
				this.OnBdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pincode", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Pincode
	{
		get
		{
			return this._Pincode;
		}
		set
		{
			if ((this._Pincode != value))
			{
				this.OnPincodeChanging(value);
				this.SendPropertyChanging();
				this._Pincode = value;
				this.SendPropertyChanged("Pincode");
				this.OnPincodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RName", DbType="NVarChar(50)")]
	public string RName
	{
		get
		{
			return this._RName;
		}
		set
		{
			if ((this._RName != value))
			{
				this.OnRNameChanging(value);
				this.SendPropertyChanging();
				this._RName = value;
				this.SendPropertyChanged("RName");
				this.OnRNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPhone", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> RPhone
	{
		get
		{
			return this._RPhone;
		}
		set
		{
			if ((this._RPhone != value))
			{
				this.OnRPhoneChanging(value);
				this.SendPropertyChanging();
				this._RPhone = value;
				this.SendPropertyChanged("RPhone");
				this.OnRPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(50)")]
	public string FileName
	{
		get
		{
			return this._FileName;
		}
		set
		{
			if ((this._FileName != value))
			{
				this.OnFileNameChanging(value);
				this.SendPropertyChanging();
				this._FileName = value;
				this.SendPropertyChanged("FileName");
				this.OnFileNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileLocation", DbType="NVarChar(50)")]
	public string FileLocation
	{
		get
		{
			return this._FileLocation;
		}
		set
		{
			if ((this._FileLocation != value))
			{
				this.OnFileLocationChanging(value);
				this.SendPropertyChanging();
				this._FileLocation = value;
				this.SendPropertyChanged("FileLocation");
				this.OnFileLocationChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
