<?xml version="1.0" encoding="utf-8"?><Database Name="HAfitnessclub" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\HAfitnessclub.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HAfitnessclubConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblJob" Member="tblJobs">
    <Type Name="tblJob">
      <Column Name="JID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Bdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pincode" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="RName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RPhone" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileLocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>